#!/usr/bin/env python
"""Generate missing pages: tea-shop, member-center, and scan WXML wrappers"""
import os, json

BASE = r"C:\Users\王晓东\Documents\高岸管理\盈隆\高岸智能管理系统\高岸ERP\prototype"

pages = {}

pages[('customer-mp','tea-shop')] = {
  "wxml": '<view class="page"><view class="header"><view class="header-title">🌿 茶品雅集</view><view class="cart-badge" bindtap="goCart">🛒<view class="badge" wx:if="{{cartCount > 0}}">{{cartCount}}</view></view></view><scroll-view class="cat-tabs" scroll-x enhanced show-scrollbar="{{false}}"><view class="cat-tab {{currentCat == \'\' ? \'active\' : \'\'}}" bindtap="switchCat" data-cat="">全部</view><view class="cat-tab {{currentCat == \'Tea\' ? \'active\' : \'\'}}" bindtap="switchCat" data-cat="Tea">🍵 茶叶</view><view class="cat-tab {{currentCat == \'Snack\' ? \'active\' : \'\'}}" bindtap="switchCat" data-cat="Snack">🍪 茶点</view><view class="cat-tab {{currentCat == \'Ware\' ? \'active\' : \'\'}}" bindtap="switchCat" data-cat="Ware">🏺 茶具</view></scroll-view><view class="product-list"><view class="product-card" wx:for="{{filteredProducts}}" wx:key="productId"><view class="product-img">{{item.image || \'📦\'}}</view><view class="product-body"><text class="product-name">{{item.name}}</text><text class="product-desc">{{item.desc}}</text><view class="product-footer"><text class="product-price">¥{{item.price}} <text class="unit">/份</text></text><view class="qty-ctrl"><view class="qty-btn {{item._qty > 0 ? \'\' : \'disabled\'}}" bindtap="decQty" data-id="{{item.productId}}">−</view><text class="qty-num">{{item._qty || 0}}</text><view class="qty-btn" bindtap="incQty" data-id="{{item.productId}}">+</view></view></view></view></view></view><view class="bottom-bar" wx:if="{{cartCount > 0}}"><view class="bottom-info"><text class="bottom-count">已选 {{cartCount}} 件</text><text class="bottom-total">¥{{cartTotal}}</text></view><view class="bottom-btn" bindtap="checkout">去结算</view></view></view>',
  "wxss": ".header { padding:14px 16px; background:#fff; border-bottom:1px solid #f0f0f0; position:sticky; top:0; z-index:10; display:flex; align-items:center; justify-content:center; }.header-title { font-size:18px; font-weight:700; color:#1a1a1a; }.cart-badge { position:absolute; right:16px; top:14px; font-size:20px; }.badge { position:absolute; top:-6px; right:-6px; background:#B8860B; color:#fff; border-radius:10px; padding:1px 6px; font-size:10px; min-width:18px; text-align:center; }.cat-tabs { display:flex; padding:12px 16px; gap:8px; background:#fff; border-bottom:1px solid #f5f5f5; white-space:nowrap; }.cat-tab { display:inline-block; padding:7px 18px; border-radius:18px; font-size:13px; background:#f5f5f5; color:#666; margin-right:8px; }.cat-tab.active { background:#5D8A6B; color:#fff; }.product-list { padding:10px 16px; }.product-card { display:flex; padding:12px; border-radius:12px; background:#fafafa; margin-bottom:10px; }.product-img { width:52px; height:52px; border-radius:10px; display:flex; align-items:center; justify-content:center; font-size:28px; flex-shrink:0; background:#f0f0f0; }.product-body { flex:1; margin-left:12px; }.product-name { font-size:14px; font-weight:600; color:#333; display:block; }.product-desc { font-size:11px; color:#999; margin-top:2px; display:block; }.product-footer { display:flex; justify-content:space-between; align-items:center; margin-top:6px; }.product-price { font-size:16px; font-weight:700; color:#B8860B; }.product-price .unit { font-size:11px; font-weight:400; color:#999; }.qty-ctrl { display:flex; align-items:center; gap:8px; }.qty-btn { width:26px; height:26px; border-radius:50%; border:1px solid #ddd; background:#fff; font-size:16px; display:flex; align-items:center; justify-content:center; color:#333; font-weight:600; }.qty-btn.disabled { opacity:.3; }.qty-num { font-size:14px; font-weight:600; min-width:20px; text-align:center; color:#333; }.bottom-bar { position:fixed; bottom:0; left:0; right:0; background:#fff; border-top:1px solid #f0f0f0; padding:10px 16px; display:flex; align-items:center; gap:12px; z-index:20; }.bottom-info { flex:1; }.bottom-count { font-size:12px; color:#999; display:block; }.bottom-total { font-size:18px; font-weight:700; color:#B8860B; }.bottom-btn { padding:12px 24px; background:linear-gradient(135deg,#5D8A6B,#7BA88E); color:#fff; border-radius:10px; font-size:15px; font-weight:600; text-align:center; }",
  "js": "const API = require('../../utils/api');Page({data:{products:[],filteredProducts:[],currentCat:'',cartCount:0,cartTotal:'0.00'},onLoad(){API.getProducts().then(products=>{const p=products.map(x=>({...x,_qty:0}));this.setData({products:p,filteredProducts:p})})},switchCat(e){const cat=e.currentTarget.dataset.cat;const list=cat?this.data.products.filter(p=>p.category===cat):this.data.products;this.setData({currentCat:cat,filteredProducts:list})},incQty(e){const id=e.currentTarget.dataset.id;const products=this.data.products.map(p=>p.productId===id?{...p,_qty:(p._qty||0)+1}:p);this.setData({products},()=>this.updateCart())},decQty(e){const id=e.currentTarget.dataset.id;const products=this.data.products.map(p=>p.productId===id&&p._qty>0?{...p,_qty:p._qty-1}:p);this.setData({products},()=>this.updateCart())},updateCart(){const items=this.data.products.filter(p=>p._qty>0);const count=items.reduce((s,p)=>s+p._qty,0);const total=items.reduce((s,p)=>s+p._qty*p.price,0);this.setData({cartCount:count,cartTotal:total.toFixed(2)})},checkout(){wx.showToast({title:'结账功能开发中',icon:'none'})},goCart(){wx.showToast({title:'购物车',icon:'none'})}})"
}

pages[('customer-mp','member-center')] = {
  "wxml": '<view class="page"><view class="profile-header"><view class="avatar">👤</view><view class="profile-info"><text class="profile-name">{{user.name || \'点击登录\'}}</text><text class="profile-level">{{user.memberLevel || \'Normal\'}}</text></view></view><view class="balance-card"><view class="balance-item"><text class="balance-label">余额</text><text class="balance-value">¥{{balance}}</text></view><view class="balance-divider"></view><view class="balance-item"><text class="balance-label">累计消费</text><text class="balance-value">¥{{totalSpent}}</text></view><view class="balance-divider"></view><view class="balance-item"><text class="balance-label">到店次数</text><text class="balance-value">{{visitCount}}次</text></view></view><view class="menu-list"><view class="menu-item" bindtap="goMyOrders"><text>📋 我的订单</text><text>›</text></view><view class="menu-item" bindtap="goMyCoupons"><text>🎫 我的优惠券</text><text>›</text></view><view class="menu-item" bindtap="goTopUp"><text>💰 充值中心</text><text>›</text></view><view class="menu-item" bindtap="goRoomControl"><text>🔒 房间智控</text><text>›</text></view></view></view>',
  "wxss": ".profile-header { padding:24px 20px; background:linear-gradient(135deg,#5D8A6B,#7BA88E); color:#fff; display:flex; align-items:center; gap:16px; }.avatar { width:60px; height:60px; border-radius:50%; background:rgba(255,255,255,.2); display:flex; align-items:center; justify-content:center; font-size:30px; }.profile-name { font-size:18px; font-weight:700; }.profile-level { font-size:12px; opacity:.8; margin-top:2px; }.balance-card { display:flex; background:#fff; padding:20px 16px; }.balance-item { flex:1; text-align:center; }.balance-label { display:block; font-size:12px; color:#999; margin-bottom:4px; }.balance-value { font-size:20px; font-weight:700; color:#B8860B; }.balance-divider { width:1px; background:#f0f0f0; }.menu-list { background:#fff; margin-top:12px; }.menu-item { display:flex; justify-content:space-between; align-items:center; padding:16px 20px; border-bottom:1px solid #f5f5f5; font-size:15px; }",
  "js": "const API = require('../../utils/api');Page({data:{user:{},balance:0,totalSpent:0,visitCount:0},onShow(){const user=API.getCurrentUser();if(user){this.setData({user,balance:user.balance||0,totalSpent:user.totalSpent||0,visitCount:user.visitCount||0});API.getBalance().then(balance=>this.setData({balance}))}},goMyOrders(){wx.switchTab({url:'/pages/my-orders/my-orders'})},goMyCoupons(){wx.navigateTo({url:'/pages/my-coupons/my-coupons'})},goTopUp(){wx.showToast({title:'充值功能开发中',icon:'none'})},goRoomControl(){wx.navigateTo({url:'/pages/room-control/room-control'})}})"
}

# Generate
count = 0
for (app, name), files in pages.items():
    dir_path = os.path.join(BASE, app, 'pages', name)
    os.makedirs(dir_path, exist_ok=True)
    for ext, content in [('.wxml', files['wxml']), ('.wxss', files['wxss']), ('.js', files['js'])]:
        with open(os.path.join(dir_path, name + ext), 'w', encoding='utf-8') as f:
            f.write(content)
    with open(os.path.join(dir_path, name + '.json'), 'w', encoding='utf-8') as f:
        json.dump({"navigationBarTitleText": {'tea-shop':'茶品雅集','member-center':'会员中心'}.get(name, name), "usingComponents": {}}, f, ensure_ascii=False)
    count += 1
    print(f"  [{app}] {name}")
print(f"\nDone! Generated {count} page sets")
