#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Generate scan pages as native WXML"""
import os, json
BASE = r"C:\Users\王晓东\Documents\高岸管理\盈隆\高岸智能管理系统\高岸ERP\prototype"

pages = {}

pages["scan-landing"] = {
  "title": "扫码落座",
  "wxml": '<view class="page"><view class="loading-state" wx:if="{{loading}}"><view class="loading-spinner"></view><text>验证中...</text></view><view class="success" wx:elif="{{verified}}"><view class="icon">&#x2705;</view><text class="name">&#x1F3E0; {{roomName}}</text><view class="btns"><button bindtap="goOrder">点单加购</button><button class="outline" bindtap="goBill">查看账单</button></view></view><view class="error" wx:else><view class="icon">&#x26A0;&#xFE0F;</view><text>{{errorMsg}}</text><button bindtap="callStaff">联系店员</button></view></view>',
  "wxss": ".page{padding:40px 24px;text-align:center}.loading-spinner{width:40px;height:40px;border:3px solid #e8e8e8;border-top-color:#5D8A6B;border-radius:50%;animation:spin .8s linear infinite;margin:0 auto 16px}@keyframes spin{to{transform:rotate(360deg)}}.icon{font-size:48px;margin-bottom:16px}.name{font-size:22px;font-weight:700;display:block;margin-bottom:24px}.btns{display:flex;flex-direction:column;gap:12px}button{width:100%;padding:14px;background:#5D8A6B;color:#fff;border:none;border-radius:10px;font-size:15px;font-weight:600}button.outline{background:#fff;color:#5D8A6B;border:1.5px solid #5D8A6B}.error .icon{color:#e53935}.error text{display:block;margin-bottom:16px;color:#666}",
  "js": 'const API = require("../../utils/api");Page({data:{loading:true,verified:false,error:false,roomId:"",roomName:"",errorMsg:""},onLoad(e){const roomId=e.room_id||"";if(!roomId){this.setData({loading:false,error:true,errorMsg:"缺少房间参数"});return}this.setData({roomId});API.scanRoomStatus(roomId).then(info=>{if(info.hasActiveOrder){this.setData({loading:false,verified:true,roomName:info.roomName})}else{this.setData({loading:false,error:true,errorMsg:info.message||"请联系店员开房"})}}).catch(()=>this.setData({loading:false,error:true,errorMsg:"网络异常"}))},goOrder(){wx.navigateTo({url:"/pages/scan-order/scan-order?room_id="+this.data.roomId})},goBill(){wx.navigateTo({url:"/pages/scan-bill/scan-bill?room_id="+this.data.roomId})},callStaff(){wx.showToast({title:"前台电话:020-88888888",icon:"none"})}})'
}

pages["scan-order"] = {
  "title": "扫码点单",
  "wxml": '<view class="page"><view class="banner">&#x1F3E0; 扫码点单加购</view><scroll-view class="tabs" scroll-x><view class="tab {{cat==&quot;&quot;?&quot;active&quot;:&quot;&quot;}}" bindtap="setCat" data-cat="">全部</view><view class="tab {{cat==&quot;Tea&quot;?&quot;active&quot;:&quot;&quot;}}" bindtap="setCat" data-cat="Tea">茶叶</view><view class="tab {{cat==&quot;Snack&quot;?&quot;active&quot;:&quot;&quot;}}" bindtap="setCat" data-cat="Snack">茶点</view></scroll-view><view class="list"><view class="item" wx:for="{{items}}" wx:key="productId"><text>{{item.name}}</text><text class="price">&#165;{{item.price}}</text><view class="qty"><text bindtap="dec" data-id="{{item.productId}}">-</text><text>{{item._qty||0}}</text><text bindtap="inc" data-id="{{item.productId}}">+</text></view></view></view><view class="bar" wx:if="{{total>0}}"><text>&#165;{{total}}</text><button bindtap="submit">挂账</button></view></view>',
  "wxss": ".banner{padding:12px 16px;background:#f0fdf4}.tabs{display:flex;padding:10px 16px;white-space:nowrap;background:#fff}.tab{display:inline-block;padding:6px 16px;border-radius:16px;font-size:13px;background:#f5f5f5;color:#666;margin-right:8px}.tab.active{background:#5D8A6B;color:#fff}.list{padding:10px 16px}.item{display:flex;align-items:center;padding:12px;background:#fafafa;border-radius:10px;margin-bottom:8px}.item text{flex:1;font-size:14px}.price{color:#B8860B;font-weight:600}.qty{display:flex;align-items:center;gap:10px}.qty text{width:26px;height:26px;border-radius:50%;border:1px solid #ddd;display:flex;align-items:center;justify-content:center;font-size:16px}.bar{position:fixed;bottom:0;left:0;right:0;background:#fff;border-top:1px solid #f0f0f0;padding:10px 16px;display:flex;align-items:center;gap:12px}.bar text{flex:1;font-size:20px;font-weight:700;color:#B8860B}.bar button{padding:12px 24px;background:#5D8A6B;color:#fff;border:none;border-radius:10px;font-size:15px;font-weight:600}",
  "js": 'const API = require("../../utils/api");Page({data:{products:[],items:[],cat:"",total:0,roomId:""},onLoad(e){this.setData({roomId:e.room_id||""});API.getProducts().then(products=>{const p=products.map(x=>({...x,_qty:0}));this.setData({products:p,items:p})})},setCat(e){const cat=e.currentTarget.dataset.cat;const list=cat?this.data.products.filter(p=>p.category===cat):this.data.products;this.setData({cat:cat,items:list})},inc(e){const id=e.currentTarget.dataset.id;const p=this.data.products.map(x=>x.productId===id?{...x,_qty:(x._qty||0)+1}:x);this.setData({products:p,items:p.filter(x=>!this.data.cat||x.category===this.data.cat)},()=>this.calc())},dec(e){const id=e.currentTarget.dataset.id;const p=this.data.products.map(x=>x.productId===id&&x._qty>0?{...x,_qty:x._qty-1}:x);this.setData({products:p,items:p.filter(x=>!this.data.cat||x.category===this.data.cat)},()=>this.calc())},calc(){const t=this.data.products.reduce((s,x)=>s+(x._qty||0)*x.price,0);this.setData({total:t.toFixed(2)})},submit(){const items=this.data.products.filter(x=>x._qty>0).map(x=>({productId:x.productId,quantity:x._qty,unitPrice:x.price}));API.createScanOrder({roomId:this.data.roomId,storeId:"ST001",items}).then(()=>{wx.showToast({title:"加购成功",icon:"success"});this.setData({products:this.data.products.map(x=>({...x,_qty:0})),total:0})}).catch(()=>wx.showToast({title:"下单失败",icon:"none"}))}})'
}

pages["scan-bill"] = {
  "title": "房间账单",
  "wxml": '<view class="page"><view class="header"><text>&#x1F3E0; 房间账单</text></view><view class="summary"><text>房费: &#165;{{roomCharge}}</text><text>加购: &#165;{{scanTotal}}</text><text class="total">待结算: &#165;{{pendingPayment}}</text></view><view class="orders"><view class="order" wx:for="{{orders}}" wx:key="orderId"><text>{{item.status}}</text><text>&#165;{{item.totalAmount}}</text><button wx:if="{{item.canCancel}}" bindtap="cancel" data-id="{{item.orderId}}">撤销</button></view></view><view class="bar"><text>&#165;{{pendingPayment}}</text><button bindtap="settle">结算</button></view></view>',
  "wxss": ".header{padding:16px;background:linear-gradient(135deg,#5D8A6B,#7BA88E);color:#fff;font-size:18px;font-weight:700}.summary{margin:12px 16px;background:#fff;border-radius:12px;padding:16px}.summary text{display:flex;justify-content:space-between;padding:6px 0;font-size:14px}.summary .total{border-top:1px solid #e8e8e8;padding-top:10px;margin-top:4px;font-weight:700;color:#B8860B}.orders{padding:0 16px}.order{display:flex;align-items:center;padding:12px;background:#fff;border-radius:10px;margin-bottom:8px}.order text{flex:1}.order button{font-size:12px;color:#e53935;background:none;border:none;padding:4px}.bar{position:fixed;bottom:0;left:0;right:0;background:#fff;border-top:1px solid #f0f0f0;padding:10px 16px;display:flex;align-items:center;gap:12px;z-index:20}.bar text{flex:1;font-size:20px;font-weight:700;color:#B8860B}.bar button{padding:12px 24px;background:#5D8A6B;color:#fff;border:none;border-radius:10px;font-size:15px;font-weight:600}",
  "js": 'const API = require("../../utils/api");Page({data:{roomId:"",roomCharge:0,scanTotal:0,pendingPayment:0,orders:[]},onLoad(e){const roomId=e.room_id||"";this.setData({roomId});API.getScanBill(roomId).then(b=>{this.setData({roomCharge:b.billSummary.roomCharge,scanTotal:b.billSummary.scanTotal,pendingPayment:b.billSummary.pendingPayment,orders:b.scanOrders})})},cancel(e){const id=e.currentTarget.dataset.id;wx.showModal({title:"确认撤销",content:"确定撤销此订单?",success:r=>{if(r.confirm)API.cancelScanOrder(id).then(()=>{wx.showToast({title:"已撤销",icon:"success"});API.getScanBill(this.data.roomId).then(b=>this.setData({orders:b.scanOrders}))})}})},settle(){API.settleScanBill(this.data.roomId,{paymentMethod:"WxPay"}).then(r=>{wx.showToast({title:"结算成功 ¥"+r.totalAmount.toFixed(2),icon:"none"});API.getScanBill(this.data.roomId).then(b=>this.setData({orders:b.scanOrders,pendingPayment:b.billSummary.pendingPayment}))})}})'
}

for name, p in pages.items():
    d = os.path.join(BASE, "customer-mp", "pages", name)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, name+".wxml"), "w", encoding="utf-8") as f: f.write(p["wxml"])
    with open(os.path.join(d, name+".wxss"), "w", encoding="utf-8") as f: f.write(p["wxss"])
    with open(os.path.join(d, name+".js"), "w", encoding="utf-8") as f: f.write(p["js"])
    with open(os.path.join(d, name+".json"), "w", encoding="utf-8") as f: json.dump({"navigationBarTitleText": p["title"]}, f, ensure_ascii=False)
    print("OK " + name)

print("All scan pages generated!")
