#!/usr/bin/env python
"""Generate all mini-program page files from templates."""
import os, json

BASE = r"C:\Users\王晓东\Documents\高岸管理\盈隆\高岸智能管理系统\高岸ERP\prototype"

def write_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"  {path}")

# ── Page templates ──

PAGES = {}

# ============ CUSTOMER MP ============

PAGES[('customer-mp','room-list')] = {
 "wxml": '<view class="page"><view class="filter-bar"><view class="filter-tab {{filterType === \'\' ? \'active\' : \'\'}}" bindtap="setFilter" data-type="">全部</view><view class="filter-tab {{filterType === \'TeaRoom\' ? \'active\' : \'\'}}" bindtap="setFilter" data-type="TeaRoom">茶室</view><view class="filter-tab {{filterType === \'MeetingRoom\' ? \'active\' : \'\'}}" bindtap="setFilter" data-type="MeetingRoom">会议室</view><view class="filter-tab {{filterType === \'Exhibition\' ? \'active\' : \'\'}}" bindtap="setFilter" data-type="Exhibition">展厅</view></view><view class="room-grid"><view class="room-card" wx:for="{{filteredRooms}}" wx:key="roomId" bindtap="goDetail" data-id="{{item.roomId}}"><view class="room-img">{{item.type === \'TeaRoom\' ? \'🍵\' : item.type === \'MeetingRoom\' ? \'💼\' : \'🏠\'}}</view><view class="room-info"><text class="room-name">{{item.name}}</text><text class="room-meta">{{item.capacity}}人 · {{item.area}}㎡</text><text class="room-price">¥{{item.pricePerHour}}<text class="unit">/时</text></text></view><text class="room-arrow">›</text></view></view><view class="empty" wx:if="{{filteredRooms.length === 0}}">暂无符合条件的房间</view></view>',
 "wxss": '.filter-bar { display:flex; padding:12px 16px; gap:8px; background:#fff; border-bottom:1px solid #f0f0f0; }\n.filter-tab { padding:6px 16px; border-radius:16px; font-size:13px; background:#f5f5f5; color:#666; }\n.filter-tab.active { background:#5D8A6B; color:#fff; }\n.room-grid { padding:12px 16px; }\n.room-card { display:flex; align-items:center; padding:14px; background:#fff; border-radius:12px; margin-bottom:10px; box-shadow:0 1px 3px rgba(0,0,0,.05); }\n.room-img { width:56px; height:56px; border-radius:10px; display:flex; align-items:center; justify-content:center; font-size:28px; background:#f0f0f0; flex-shrink:0; }\n.room-info { flex:1; margin-left:12px; }\n.room-name { font-size:15px; font-weight:600; color:#333; display:block; }\n.room-meta { font-size:12px; color:#999; margin-top:2px; display:block; }\n.room-price { font-size:17px; font-weight:700; color:#B8860B; margin-top:4px; display:block; }\n.room-price .unit { font-size:11px; font-weight:400; color:#999; }\n.room-arrow { color:#ccc; font-size:20px; padding:0 4px; }\n.empty { text-align:center; padding:60px; color:#ccc; font-size:14px; }',
 "js": 'const API = require(\'../../utils/api\')\nPage({\n  data: { rooms: [], filteredRooms: [], filterType: \'\' },\n  onLoad() { API.getRooms(true).then(rooms => this.setData({ rooms, filteredRooms: rooms })) },\n  setFilter(e) {\n    const type = e.currentTarget.dataset.type\n    const list = type ? this.data.rooms.filter(r => r.type === type) : this.data.rooms\n    this.setData({ filterType: type, filteredRooms: list })\n  },\n  goDetail(e) { wx.navigateTo({ url: \'/pages/room-detail/room-detail?roomId=\' + e.currentTarget.dataset.id }) }\n})'
}

PAGES[('customer-mp','room-detail')] = {
 "wxml": '<view class="page"><view class="hero">{{room.type === \'TeaRoom\' ? \'🍵\' : room.type === \'MeetingRoom\' ? \'💼\' : \'🏠\'}} {{room.name}}</view><view class="info-card"><view class="info-row"><text class="info-label">类型</text><text>{{room.type === \'TeaRoom\' ? \'茶室\' : room.type === \'MeetingRoom\' ? \'会议室\' : room.type === \'Exhibition\' ? \'展厅\' : \'工作间\'}}</text></view><view class="info-row"><text class="info-label">容纳人数</text><text>{{room.capacity}}人</text></view><view class="info-row"><text class="info-label">面积</text><text>{{room.area}}㎡</text></view><view class="info-row"><text class="info-label">价格</text><text class="price">¥{{room.pricePerHour}}/时</text></text></view><view class="info-row"><text class="info-label">设施</text><view class="tags"><text class="tag" wx:for="{{room.facilities}}" wx:key="*this">{{item}}</text></view></view></view></view><view class="section"><text class="section-title">选择日期与时段</text></view><view class="booking-card"><picker mode="date" value="{{selectedDate}}" bindchange="onDateChange"><view class="picker-row"><text class="picker-label">日期</text><text>{{selectedDate}}</text></view></picker><view class="time-row"><picker mode="time" value="{{startTime}}" bindchange="onStartChange"><view class="picker-row"><text class="picker-label">开始</text><text>{{startTime}}</text></view></picker><text class="time-sep">至</text><picker mode="time" value="{{endTime}}" bindchange="onEndChange"><view class="picker-row"><text class="picker-label">结束</text><text>{{endTime}}</text></view></picker></view><view class="total-row"><text>预计费用</text><text class="price">¥{{estimatedTotal}}</text></view></view><view class="bottom-bar"><button class="book-btn" bindtap="goBooking">立即预约</button></view></view>',
 "wxss": '.hero { padding:40px 20px; background:linear-gradient(135deg,#5D8A6B,#7BA88E); color:#fff; font-size:24px; font-weight:700; text-align:center; }\n.info-card { margin:12px 16px; background:#fff; border-radius:12px; padding:16px; }\n.info-row { display:flex; justify-content:space-between; align-items:center; padding:8px 0; border-bottom:1px solid #f5f5f5; font-size:14px; }\n.info-row:last-child { border-bottom:none; }\n.info-label { color:#999; }\n.price { color:#B8860B; font-weight:600; }\n.tags { display:flex; gap:4px; flex-wrap:wrap; }\n.tag { font-size:11px; background:#f0f0f0; padding:2px 8px; border-radius:4px; color:#666; }\n.section-title { font-size:15px; font-weight:600; padding:16px 16px 8px; display:block; }\n.booking-card { margin:0 16px; background:#fff; border-radius:12px; padding:16px; }\n.picker-row { display:flex; justify-content:space-between; align-items:center; padding:8px 0; font-size:14px; }\n.picker-label { color:#999; }\n.time-row { display:flex; align-items:center; gap:12px; }\n.time-sep { color:#ccc; }\n.total-row { display:flex; justify-content:space-between; align-items:center; padding:12px 0 0; border-top:1px solid #f0f0f0; margin-top:8px; font-size:15px; }\n.bottom-bar { position:fixed; bottom:0; left:0; right:0; padding:12px 16px; background:#fff; border-top:1px solid #f0f0f0; }\n.book-btn { width:100%; padding:14px; background:linear-gradient(135deg,#5D8A6B,#7BA88E); color:#fff; border:none; border-radius:10px; font-size:16px; font-weight:600; text-align:center; }',
 "js": 'const API = require(\'../../utils/api\')\nPage({\n  data: { room: {}, roomId: \'\', selectedDate: \'\', startTime: \'10:00\', endTime: \'12:00\', estimatedTotal: 0 },\n  onLoad(e) {\n    const roomId = e.roomId || \'RM001\'\n    const today = new Date().toISOString().slice(0,10)\n    this.setData({ roomId, selectedDate: today })\n    API.getRoomById(roomId).then(room => this.setData({ room }, () => this.calcTotal()))\n  },\n  onDateChange(e) { this.setData({ selectedDate: e.detail.value }, () => this.calcTotal()) },\n  onStartChange(e) { this.setData({ startTime: e.detail.value }, () => this.calcTotal()) },\n  onEndChange(e) { this.setData({ endTime: e.detail.value }, () => this.calcTotal()) },\n  calcTotal() {\n    const hours = parseFloat(this.data.endTime) - parseFloat(this.data.startTime)\n    const total = Math.max(0, hours * (this.data.room.pricePerHour || 0))\n    this.setData({ estimatedTotal: total.toFixed(2) })\n  },\n  goBooking() {\n    wx.navigateTo({ url: \'/pages/booking-confirm/booking-confirm?roomId=\' + this.data.roomId + \'&date=\' + this.data.selectedDate + \'&start=\' + this.data.startTime + \'&end=\' + this.data.endTime + \'&total=\' + this.data.estimatedTotal })\n  }\n})'
}

PAGES[('customer-mp','booking-confirm')] = {
 "wxml": '<view class="page"><view class="confirm-card"><text class="confirm-title">确认预约信息</text><view class="confirm-row"><text class="label">房间</text><text>{{roomName || \'大茶室C\'}}</text></view><view class="confirm-row"><text class="label">日期</text><text>{{dateStr}}</text></view><view class="confirm-row"><text class="label">时段</text><text>{{startTime}}-{{endTime}}</text></view><view class="confirm-row"><text class="label">时长</text><text>{{duration}}小时</text></view><view class="confirm-row total"><text class="label">费用</text><text class="price">¥{{totalAmount}}</text></view></view><view class="payment-card"><text class="payment-title">支付方式</text><view class="payment-option {{paymentMethod === \'WeChat\' ? \'active\' : \'\'}}" bindtap="setPayment" data-method="WeChat">💳 微信支付</view><view class="payment-option {{paymentMethod === \'Balance\' ? \'active\' : \'\'}}" bindtap="setPayment" data-method="Balance">💰 余额支付 (¥{{balance}})</view><view class="payment-option {{paymentMethod === \'AliPay\' ? \'active\' : \'\'}}" bindtap="setPayment" data-method="AliPay">📱 支付宝</view></view><view class="bottom-bar"><button class="submit-btn" bindtap="submitBooking">确认预约 · ¥{{totalAmount}}</button></view></view>',
 "wxss": '.confirm-card { margin:12px 16px; background:#fff; border-radius:12px; padding:16px; }\n.confirm-title { font-size:16px; font-weight:600; display:block; margin-bottom:12px; }\n.confirm-row { display:flex; justify-content:space-between; padding:8px 0; border-bottom:1px solid #f5f5f5; font-size:14px; }\n.confirm-row.total { border-top:2px solid #e8e8e8; margin-top:8px; padding-top:12px; font-size:16px; font-weight:600; }\n.confirm-row .label { color:#999; }\n.price { color:#B8860B; }\n.payment-card { margin:0 16px; background:#fff; border-radius:12px; padding:16px; }\n.payment-title { font-size:15px; font-weight:600; display:block; margin-bottom:10px; }\n.payment-option { padding:14px 16px; border:1.5px solid #e8e8e8; border-radius:10px; margin-bottom:8px; font-size:14px; }\n.payment-option.active { border-color:#5D8A6B; background:#f0fdf4; color:#2e7d32; }\n.bottom-bar { position:fixed; bottom:0; left:0; right:0; padding:12px 16px; background:#fff; border-top:1px solid #f0f0f0; }\n.submit-btn { width:100%; padding:14px; background:linear-gradient(135deg,#5D8A6B,#7BA88E); color:#fff; border:none; border-radius:10px; font-size:16px; font-weight:600; }',
 "js": 'const API = require(\'../../utils/api\')\nPage({\n  data: { roomId: \'\', roomName: \'\', dateStr: \'\', startTime: \'10:00\', endTime: \'12:00\', duration: 2, totalAmount: \'0.00\', paymentMethod: \'WeChat\', balance: 0 },\n  onLoad(e) {\n    const d = this.data\n    this.setData({ roomId: e.roomId || \'\', dateStr: e.date || \'\', startTime: e.start || \'10:00\', endTime: e.end || \'12:00\', totalAmount: e.total || \'0.00\', duration: ((parseFloat(e.end || \'12\') - parseFloat(e.start || \'10\')) || 2).toString() })\n    if (e.roomId) API.getRoomById(e.roomId).then(r => this.setData({ roomName: r.name })).catch(() => {})\n    API.getBalance().then(b => this.setData({ balance: b }))\n  },\n  setPayment(e) { this.setData({ paymentMethod: e.currentTarget.dataset.method }) },\n  submitBooking() {\n    const d = this.data\n    API.createBooking({ roomId: d.roomId, roomName: d.roomName, date: d.dateStr, start: d.startTime, end: d.endTime, duration: parseFloat(d.duration), amount: parseFloat(d.totalAmount), paymentMethod: d.paymentMethod }).then(() => {\n      wx.showToast({ title: \'✅ 预约成功！\', icon: \'success\', duration: 2000 })\n      setTimeout(() => wx.switchTab({ url: \'/pages/my-orders/my-orders\' }), 2000)\n    }).catch(err => wx.showToast({ title: \'❌ \' + (err.message || \'预约失败\'), icon: \'none\' }))\n  }\n})'
}

PAGES[('customer-mp','my-orders')] = {
 "wxml": '<view class="page"><view class="filter-bar"><view class="filter-tab {{filter === \'all\' ? \'active\' : \'\'}}" bindtap="setFilter" data-filter="all">全部</view><view class="filter-tab {{filter === \'InUse\' ? \'active\' : \'\'}}" bindtap="setFilter" data-filter="InUse">进行中</view><view class="filter-tab {{filter === \'Booked\' ? \'active\' : \'\'}}" bindtap="setFilter" data-filter="Booked">已预订</view><view class="filter-tab {{filter === \'Completed\' ? \'active\' : \'\'}}" bindtap="setFilter" data-filter="Completed">已完成</view></view><view class="order-list"><view class="order-card" wx:for="{{filteredOrders}}" wx:key="orderId"><view class="order-card-header"><text>{{item.roomName || \'房间\'}}</text><text class="order-status {{item.status.toLowerCase()}}">{{item.statusLabel || item.status}}</text></view><text class="order-time">{{item.start}} - {{item.end}}</text><view class="order-card-footer"><text class="order-amount">¥{{item.amount || 0}}</text><text class="order-paid">{{item.paymentMethod}}</text></view></view></view><view class="empty" wx:if="{{filteredOrders.length === 0}}">暂无订单</view></view>',
 "wxss": '.filter-bar { display:flex; padding:12px 16px; gap:8px; background:#fff; border-bottom:1px solid #f0f0f0; }\n.filter-tab { padding:6px 16px; border-radius:16px; font-size:13px; background:#f5f5f5; color:#666; }\n.filter-tab.active { background:#5D8A6B; color:#fff; }\n.order-list { padding:12px 16px; }\n.order-card { padding:14px; background:#fff; border-radius:12px; margin-bottom:10px; }\n.order-card-header { display:flex; justify-content:space-between; align-items:center; margin-bottom:6px; font-size:15px; font-weight:600; }\n.order-status { font-size:11px; padding:2px 8px; border-radius:10px; }\n.order-status.inuse { background:#e3f2fd; color:#1565c0; }\n.order-status.booked { background:#f3e5f5; color:#7b1fa2; }\n.order-status.completed { background:#f0fdf4; color:#2e7d32; }\n.order-time { font-size:12px; color:#999; display:block; }\n.order-card-footer { display:flex; justify-content:space-between; align-items:center; margin-top:8px; border-top:1px solid #f5f5f5; padding-top:8px; }\n.order-amount { font-size:16px; font-weight:700; color:#B8860B; }\n.order-paid { font-size:11px; color:#999; }\n.empty { text-align:center; padding:60px; color:#ccc; font-size:14px; }',
 "js": 'const API = require(\'../../utils/api\')\nPage({\n  data: { orders: [], filteredOrders: [], filter: \'all\' },\n  onShow() { this.loadOrders() },\n  loadOrders() {\n    API.getUserOrders().then(orders => {\n      const mapped = orders.map(o => ({ ...o, statusLabel: { InUse:\'使用中\', Booked:\'已预订\', Completed:\'已完成\', Cancelled:\'已取消\' }[o.status] || o.status }))\n      this.setData({ orders: mapped }, () => this.applyFilter())\n    })\n  },\n  setFilter(e) { this.setData({ filter: e.currentTarget.dataset.filter }, () => this.applyFilter()) },\n  applyFilter() {\n    const f = this.data.filter\n    const list = f === \'all\' ? this.data.orders : this.data.orders.filter(o => o.status === f)\n    this.setData({ filteredOrders: list })\n  }\n})'
}

PAGES[('customer-mp','my-coupons')] = {
 "wxml": '<view class="page"><view class="header"><text class="header-title">🎫 我的优惠券</text></view><view class="coupon-list"><view class="coupon-card" wx:for="{{coupons}}" wx:key="code"><view class="coupon-left"><text class="coupon-value">¥{{item.value}}</text><text class="coupon-type">{{item.type === \'discount\' ? \'满减券\' : \'代金券\'}}</text></view><view class="coupon-right"><text class="coupon-desc">{{item.desc}}</text><text class="coupon-platform">{{item.platform === \'System\' ? \'系统发放\' : item.platform}}</text><view class="coupon-status {{item.used ? \'used\' : \'active\'}}">{{item.used ? \'已使用\' : \'可使用\'}}</view></view></view></view><view class="empty" wx:if="{{coupons.length === 0}}">暂无优惠券</view></view>',
 "wxss": '.header { padding:14px 16px; background:#fff; border-bottom:1px solid #f0f0f0; }\n.header-title { font-size:17px; font-weight:700; }\n.coupon-list { padding:12px 16px; }\n.coupon-card { display:flex; background:#fff; border-radius:10px; margin-bottom:10px; overflow:hidden; border:1px solid #f0f0f0; }\n.coupon-left { width:80px; background:linear-gradient(135deg,#B8860B,#D4A84B); color:#fff; display:flex; flex-direction:column; align-items:center; justify-content:center; padding:12px; }\n.coupon-value { font-size:22px; font-weight:700; }\n.coupon-type { font-size:10px; opacity:.8; margin-top:2px; }\n.coupon-right { flex:1; padding:12px; }\n.coupon-desc { font-size:13px; color:#333; display:block; }\n.coupon-platform { font-size:11px; color:#999; margin-top:2px; display:block; }\n.coupon-status { font-size:11px; margin-top:6px; display:inline-block; padding:2px 8px; border-radius:4px; }\n.coupon-status.active { background:#f0fdf4; color:#2e7d32; }\n.coupon-status.used { background:#f5f5f5; color:#999; }\n.empty { text-align:center; padding:60px; color:#ccc; font-size:14px; }',
 "js": 'const API = require(\'../../utils/api\')\nPage({ data: { coupons: [] }, onLoad() { API.getUserCoupons().then(coupons => this.setData({ coupons })) } })'
}

PAGES[('customer-mp','coupon-verify')] = {
 "wxml": '<view class="page"><view class="verify-card"><text class="verify-title">验券</text><input class="verify-input" placeholder="输入券码" value="{{code}}" bindinput="onCode" /><button class="verify-btn" bindtap="doVerify" disabled="{{!code}}">核 销</button><view class="verify-result" wx:if="{{result}}"><text wx:if="{{result.success}}" style="color:#00A870">✅ {{result.desc}} — ¥{{result.value}}</text><text wx:else style="color:#e53935">❌ {{result.error}}</text></view><text class="verify-hint">支持平台券（美团/抖音）和系统券核销</text></view></view>',
 "wxss": '.page { padding:40px 24px; }\n.verify-card { background:#fff; border-radius:12px; padding:24px; }\n.verify-title { font-size:18px; font-weight:600; display:block; margin-bottom:16px; text-align:center; }\n.verify-input { width:100%; padding:14px; border:1.5px solid #ddd; border-radius:10px; font-size:16px; text-align:center; }\n.verify-btn { width:100%; padding:14px; background:#5D8A6B; color:#fff; border:none; border-radius:10px; font-size:15px; font-weight:600; margin-top:12px; }\n.verify-btn[disabled] { background:#ccc; }\n.verify-result { margin-top:12px; text-align:center; font-size:14px; display:block; }\n.verify-hint { font-size:12px; color:#999; margin-top:16px; display:block; text-align:center; }',
 "js": 'const API = require(\'../../utils/api\')\nPage({ data: { code: \'\', result: null }, onCode(e) { this.setData({ code: e.detail.value, result: null }) }, doVerify() { API.verifyCoupon(this.data.code).then(r => this.setData({ result: { success: true, ...r } })).catch(err => this.setData({ result: { success: false, error: err.message } })) } })'
}

PAGES[('customer-mp','room-control')] = {
 "wxml": '<view class="page"><view class="room-header">{{roomName}} 智控</view><view class="scene-grid"><view class="scene-btn" wx:for="{{scenes}}" wx:key="sceneId" style="background:{{item.color}}20; border-color:{{item.color}}" bindtap="activateScene" data-id="{{item.sceneId}}"><text style="font-size:20px">{{item.icon}}</text><text style="font-size:12px; margin-top:4px; color:{{item.color}}">{{item.name}}</text></view></view><text class="section-title">设备控制</text><view class="device-list"><view class="device-item" wx:for="{{devices}}" wx:key="deviceId"><view class="device-icon">{{item.typeIcon || \'📡\'}}</view><view class="device-info"><text class="device-name">{{item.typeLabel || item.type}}</text><text class="device-status {{item.status === \'Online\' ? \'online\' : \'offline\'}}">{{item.status === \'Online\' ? \'在线\' : \'离线\'}}</text></view><view class="device-control" wx:if="{{item.type === \'Light\'}}"><slider value="{{item.brightness || 0}}" min="0" max="100" show-value bindchanging="onLightChange" data-id="{{item.deviceId}}" /></view><switch wx:elif="{{item.type === \'AC\'}}" checked="{{item.mode === \'cool\'}}" bindchange="onAcToggle" data-id="{{item.deviceId}}" /><switch wx:elif="{{item.type === \'Speaker\'}}" checked="{{item.playing}}" bindchange="onSpeakerToggle" data-id="{{item.deviceId}}" /><switch wx:elif="{{item.type === \'Curtain\'}}" checked="{{item.position === \'open\'}}" bindchange="onCurtainToggle" data-id="{{item.deviceId}}" /></view></view></view>',
 "wxss": '.room-header { padding:16px; background:linear-gradient(135deg,#5D8A6B,#7BA88E); color:#fff; font-size:18px; font-weight:700; }\n.scene-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:10px; padding:16px; background:#fff; margin-bottom:12px; }\n.scene-btn { display:flex; flex-direction:column; align-items:center; justify-content:center; padding:14px 8px; border-radius:12px; border:1.5px solid #ddd; background:#f9f9f9; }\n.section-title { display:block; padding:0 16px 8px; font-size:14px; font-weight:600; color:#666; }\n.device-list { padding:0 16px; }\n.device-item { display:flex; align-items:center; padding:14px; background:#fff; border-radius:10px; margin-bottom:8px; }\n.device-icon { font-size:22px; margin-right:12px; }\n.device-info { flex:1; }\n.device-name { font-size:14px; font-weight:500; display:block; }\n.device-status { font-size:11px; }\n.device-status.online { color:#00A870; }\n.device-status.offline { color:#e53935; }\n.device-control { width:120px; }',
 "js": 'const API = require(\'../../utils/api\')\nPage({\n  data: { roomId: \'\', roomName: \'房间\', devices: [], scenes: [] },\n  onLoad(e) {\n    const roomId = e.roomId || \'RM004\'\n    this.setData({ roomId })\n    Promise.all([\n      API.getRoomDevices(roomId),\n      Promise.resolve([{sceneId:\'SC001\',name:\'迎宾模式\',icon:\'👋\',color:\'#07c160\'},{sceneId:\'SC002\',name:\'茶艺模式\',icon:\'🍵\',color:\'#e37318\'},{sceneId:\'SC003\',name:\'会议模式\',icon:\'💼\',color:\'#0052d9\'}])\n    ]).then(([devices, scenes]) => {\n      this.setData({ devices: devices.map(d => ({ ...d, typeLabel: {Lock:\'门锁\',AC:\'空调\',Light:\'灯光\',Curtain:\'窗帘\',Speaker:\'音响\'}[d.type] || d.type, typeIcon: {Lock:\'🔒\',AC:\'❄️\',Light:\'💡\',Curtain:\'🪟\',Speaker:\'🔊\'}[d.type] || \'📡\' })), scenes })\n    })\n  },\n  activateScene(e) { API.executeScene(this.data.roomId, e.currentTarget.dataset.id).then(() => wx.showToast({ title: \'场景已执行\', icon: \'none\' })) },\n  onLightChange(e) { API.controlDevice(e.currentTarget.dataset.id, { brightness: e.detail.value }).catch(() => {}) },\n  onAcToggle(e) { API.controlDevice(e.currentTarget.dataset.id, { mode: e.detail.value ? \'cool\' : \'off\' }).catch(() => {}) },\n  onSpeakerToggle(e) { API.controlDevice(e.currentTarget.dataset.id, { playing: e.detail.value }).catch(() => {}) },\n  onCurtainToggle(e) { API.controlDevice(e.currentTarget.dataset.id, { position: e.detail.value ? \'open\' : \'closed\' }).catch(() => {}) }\n})'
}

# ============ STAFF MP ============

PAGES[('staff-mp','login')] = {
 "wxml": '<view class="page"><view class="logo"><view class="logo-icon">🏢</view><view class="logo-name">高岸ERP</view><view class="logo-sub">店员工作台</view></view><view class="form"><view class="form-group"><text class="form-label">用户名</text><input class="form-input" placeholder="请输入用户名" value="{{username}}" bindinput="onUsername" /></view><view class="form-group"><text class="form-label">密码</text><input class="form-input" type="safe-password" placeholder="请输入密码" value="{{password}}" bindinput="onPassword" /></view><button class="login-btn" disabled="{{!username || !password}}" bindtap="doLogin" loading="{{loading}}">登 录</button><view class="error-msg" hidden="{{!error}}">{{error}}</view><view class="hint">演示账号：任意用户名 + 密码 8888</view></view></view>',
 "wxss": '.page { padding: 40px 28px; min-height: 100vh; }\n.logo { text-align: center; margin-bottom: 32px; }\n.logo-icon { font-size: 48px; }\n.logo-name { font-size: 20px; font-weight: 700; color: #1a365d; margin-top: 8px; }\n.logo-sub { font-size: 12px; color: #999; margin-top: 4px; }\n.form-group { margin-bottom: 20px; }\n.form-label { font-size: 13px; color: #333; font-weight: 500; margin-bottom: 6px; display: block; }\n.form-input { width: 100%; padding: 14px; border: 1.5px solid #e5e5e5; border-radius: 10px; font-size: 15px; }\n.login-btn { width: 100%; padding: 16px; border-radius: 12px; background: #0052d9; color: #fff; font-size: 16px; font-weight: 600; margin-top: 8px; }\n.login-btn[disabled] { background: #ccc; }\n.error-msg { color: #d54941; font-size: 13px; text-align: center; margin-top: 12px; }\n.hint { font-size: 12px; color: #999; margin-top: 16px; text-align: center; }',
 "js": 'const API = require(\'../../utils/api\')\nPage({\n  data: { username: \'admin\', password: \'8888\', loading: false, error: \'\' },\n  onUsername(e) { this.setData({ username: e.detail.value }) },\n  onPassword(e) { this.setData({ password: e.detail.value }) },\n  doLogin() {\n    if (!this.data.username || !this.data.password) return\n    this.setData({ loading: true, error: \'\' })\n    API.login(this.data.username, this.data.password).then(user => {\n      wx.reLaunch({ url: \'/pages/dashboard/dashboard\' })\n    }).catch(err => {\n      this.setData({ error: err.message || \'登录失败\', loading: false })\n    })\n  }\n})'
}

PAGES[('staff-mp','dashboard')] = {
 "wxml": '<view class="page"><view class="header"><text class="header-title">📊 工作台</text><text class="header-store">{{storeName}}</text></view><view class="stats-grid"><view class="stat-card"><text class="stat-num">{{stats.roomCount.inUse}}</text><text class="stat-label">使用中</text></view><view class="stat-card"><text class="stat-num">¥{{stats.todayRevenue}}</text><text class="stat-label">今日收入</text></view><view class="stat-card"><text class="stat-num">{{stats.todayOrders}}</text><text class="stat-label">今日订单</text></view><view class="stat-card"><text class="stat-num">{{stats.pendingTasks}}</text><text class="stat-label">待办任务</text></view></view><view class="quick-actions"><view class="action-item" bindtap="goRoomStatus">🏠 房态</view><view class="action-item" bindtap="goDeviceMonitor">📡 设备</view><view class="action-item" bindtap="goCleaning">🧹 保洁</view><view class="action-item" bindtap="goOrders">📋 订单</view><view class="action-item" bindtap="goTodo">✅ 待办</view><view class="action-item" bindtap="goProfile">👤 我的</view></view><view class="section"><text class="section-title">待办事项</text></view><view class="todo-list"><view class="todo-item {{item.priority === \'high\' ? \'high\' : \'\'}}" wx:for="{{todos}}" wx:key="id" bindtap="goTodo"><text class="todo-title">{{item.title}}</text><text class="todo-deadline">{{item.deadline}}</text></view></view></view>',
 "wxss": '.header { padding:14px 16px; background:#fff; border-bottom:1px solid #f0f0f0; display:flex; justify-content:space-between; align-items:center; }\n.header-title { font-size:18px; font-weight:700; }\n.header-store { font-size:12px; color:#666; }\n.stats-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:10px; padding:16px; background:#fff; margin-bottom:12px; }\n.stat-card { text-align:center; padding:12px 4px; background:#f5f7fa; border-radius:10px; }\n.stat-num { display:block; font-size:22px; font-weight:700; color:#0052d9; }\n.stat-label { font-size:11px; color:#999; margin-top:4px; display:block; }\n.quick-actions { display:grid; grid-template-columns:repeat(3,1fr); gap:10px; padding:16px; background:#fff; margin-bottom:12px; }\n.action-item { text-align:center; padding:16px 8px; background:#f5f7fa; border-radius:10px; font-size:14px; }\n.section-title { font-size:15px; font-weight:600; padding:0 16px; margin-bottom:10px; display:block; }\n.todo-list { padding:0 16px; }\n.todo-item { padding:12px 14px; background:#fff; border-radius:8px; margin-bottom:8px; display:flex; justify-content:space-between; align-items:center; font-size:13px; }\n.todo-item.high { border-left:3px solid #e53935; }\n.todo-deadline { color:#999; font-size:11px; }',
 "js": 'const API = require(\'../../utils/api\')\nPage({\n  data: { storeName: \'盈隆店\', stats: { roomCount: { inUse: 0 }, todayRevenue: 0, todayOrders: 0, pendingTasks: 0 }, todos: [] },\n  onShow() {\n    API.getDashboardStats().then(stats => this.setData({ stats }))\n    API.getTodos().then(todos => this.setData({ todos }))\n  },\n  goRoomStatus() { wx.navigateTo({ url: \'/pages/room-status/room-status\' }) },\n  goDeviceMonitor() { wx.navigateTo({ url: \'/pages/device-monitor/device-monitor\' }) },\n  goCleaning() { wx.navigateTo({ url: \'/pages/cleaning-task/cleaning-task\' }) },\n  goOrders() { wx.navigateTo({ url: \'/pages/order-management/order-management\' }) },\n  goTodo() { wx.navigateTo({ url: \'/pages/todo/todo\' }) },\n  goProfile() { wx.navigateTo({ url: \'/pages/profile/profile\' }) }\n})'
}

PAGES[('staff-mp','room-status')] = {
 "wxml": '<view class="page"><view class="header"><text class="header-title">🏠 房态管理</text></view><view class="room-grid"><view class="room-card" wx:for="{{rooms}}" wx:key="roomId"><view class="room-status-dot" style="background:{{item.statusColor}}"></view><view class="room-info"><text class="room-name">{{item.name}}</text><text class="room-type">{{item.type === \'TeaRoom\' ? \'茶室\' : item.type === \'MeetingRoom\' ? \'会议室\' : \'其他\'}} · {{item.capacity}}人</text></view><view class="room-right"><text class="room-status-label" style="color:{{item.statusColor}}">{{item.statusLabel}}</text><text class="room-order-info" wx:if="{{item.currentOrder}}">{{item.currentOrder.customerName}} {{item.currentOrder.start}}-{{item.currentOrder.end}}</text></view></view></view></view>',
 "wxss": '.header { padding:14px 16px; background:#fff; border-bottom:1px solid #f0f0f0; }\n.header-title { font-size:18px; font-weight:700; }\n.room-grid { padding:12px 16px; }\n.room-card { display:flex; align-items:center; padding:14px; background:#fff; border-radius:10px; margin-bottom:8px; }\n.room-status-dot { width:10px; height:10px; border-radius:50%; margin-right:12px; flex-shrink:0; }\n.room-info { flex:1; }\n.room-name { font-size:15px; font-weight:600; display:block; }\n.room-type { font-size:11px; color:#999; display:block; margin-top:2px; }\n.room-right { text-align:right; }\n.room-status-label { font-size:13px; font-weight:600; display:block; }\n.room-order-info { font-size:11px; color:#999; display:block; margin-top:2px; }',
 "js": 'const API = require(\'../../utils/api\')\nPage({ data: { rooms: [] }, onShow() { API.getRoomStatusList().then(rooms => this.setData({ rooms })) } })'
}

PAGES[('staff-mp','device-monitor')] = {
 "wxml": '<view class="page"><view class="header"><text class="header-title">📡 设备监控</text><text class="header-stats">在线 {{stats.online}}/{{stats.total}} · {{stats.rate}}</text></view><picker mode="selector" range="{{roomOptions}}" bindchange="onRoomChange"><view class="picker-bar">当前：{{selectedRoomName}} ▼</view></picker><view class="device-list"><view class="device-item" wx:for="{{devices}}" wx:key="deviceId"><text class="device-icon">{{item.typeIcon}}</text><view class="device-info"><text class="device-name">{{item.typeLabel}}</text><text class="device-id">{{item.deviceId}}</text></view><view class="device-status {{item.status === \'Online\' ? \'online\' : \'offline\'}}">{{item.status === \'Online\' ? \'在线\' : \'离线\'}}</view></view></view></view>',
 "wxss": '.header { padding:14px 16px; background:#fff; border-bottom:1px solid #f0f0f0; display:flex; justify-content:space-between; align-items:center; }\n.header-title { font-size:18px; font-weight:700; }\n.header-stats { font-size:12px; color:#666; }\n.picker-bar { padding:10px 16px; background:#f9f9f9; font-size:14px; }\n.device-list { padding:12px 16px; }\n.device-item { display:flex; align-items:center; padding:12px; background:#fff; border-radius:8px; margin-bottom:6px; }\n.device-icon { font-size:20px; width:32px; }\n.device-info { flex:1; }\n.device-name { font-size:14px; font-weight:500; display:block; }\n.device-id { font-size:11px; color:#999; display:block; }\n.device-status { font-size:12px; padding:2px 8px; border-radius:4px; }\n.device-status.online { background:#f0fdf4; color:#00A870; }\n.device-status.offline { background:#fce4e4; color:#e53935; }',
 "js": 'const API = require(\'../../utils/api\')\nPage({\n  data: { rooms: [], devices: [], stats: { total: 0, online: 0, rate: \'0%\' }, selectedRoomId: \'\', selectedRoomName: \'全部房间\', roomOptions: [\'全部房间\'] },\n  onShow() {\n    Promise.all([API.getRoomStatusList(), API.getDeviceList(), API.getDeviceStats()]).then(([rooms, devices, stats]) => {\n      const names = rooms.map(r => r.name)\n      this.setData({ rooms, devices, stats, roomOptions: [\'全部房间\', ...names] })\n    })\n  },\n  onRoomChange(e) {\n    const idx = e.detail.value\n    const name = this.data.roomOptions[idx]\n    if (idx === 0) {\n      API.getDeviceList().then(devices => this.setData({ devices, selectedRoomId: \'\', selectedRoomName: name }))\n    } else {\n      const room = this.data.rooms[idx - 1]\n      API.getDeviceList(room.roomId).then(devices => this.setData({ devices, selectedRoomId: room.roomId, selectedRoomName: name }))\n    }\n  }\n})'
}

PAGES[('staff-mp','cleaning-task')] = {
 "wxml": '<view class="page"><view class="header"><text class="header-title">🧹 保洁任务</text></view><view class="task-section"><text class="task-section-title">待处理</text><view class="task-card urgent" wx:for="{{pending}}" wx:key="taskId"><view class="task-top"><text class="task-room">{{item.roomName}}</text><text class="task-priority">{{item.priority === \'High\' ? \'紧急\' : \'普通\'}}</text></view><text class="task-meta">{{item.type === \'FullClean\' ? \'全面清洁\' : \'快速清洁\'}} · 截止 {{item.deadline?.slice(11,16) || \'\'}}</text><view class="task-btns"><button class="task-btn accept" bindtap="acceptTask" data-id="{{item.taskId}}">接单</button></view></view><view class="empty" wx:if="{{pending.length === 0}}">暂无待处理任务</view></view><view class="task-section"><text class="task-section-title">进行中</text><view class="task-card" wx:for="{{inProgress}}" wx:key="taskId"><view class="task-top"><text class="task-room">{{item.roomName}}</text></view><text class="task-meta">{{item.type === \'FullClean\' ? \'全面清洁\' : \'快速清洁\'}}</text><view class="task-btns"><button class="task-btn complete" bindtap="completeTask" data-id="{{item.taskId}}">完成</button></view></view></view></view>',
 "wxss": '.header { padding:14px 16px; background:#fff; border-bottom:1px solid #f0f0f0; }\n.header-title { font-size:18px; font-weight:700; }\n.task-section { padding:12px 16px; }\n.task-section-title { font-size:14px; font-weight:600; color:#666; display:block; margin-bottom:8px; }\n.task-card { background:#fff; border-radius:10px; padding:14px; margin-bottom:8px; }\n.task-card.urgent { border-left:3px solid #e53935; }\n.task-top { display:flex; justify-content:space-between; align-items:center; margin-bottom:4px; }\n.task-room { font-size:15px; font-weight:600; }\n.task-priority { font-size:11px; color:#e53935; }\n.task-meta { font-size:12px; color:#999; display:block; margin-bottom:8px; }\n.task-btns { display:flex; gap:8px; }\n.task-btn { flex:1; padding:10px; border-radius:8px; border:none; font-size:14px; font-weight:600; }\n.task-btn.accept { background:#0052d9; color:#fff; }\n.task-btn.complete { background:#00A870; color:#fff; }\n.empty { text-align:center; padding:30px; color:#ccc; font-size:13px; }',
 "js": 'const API = require(\'../../utils/api\')\nPage({\n  data: { pending: [], inProgress: [] },\n  onShow() { API.getCleaningTasks().then(t => this.setData({ pending: t.pending, inProgress: t.inProgress })) },\n  acceptTask(e) { API.acceptCleaningTask(e.currentTarget.dataset.id).then(() => this.onShow()) },\n  completeTask(e) { API.completeCleaningTask(e.currentTarget.dataset.id).then(() => this.onShow()) }\n})'
}

PAGES[('staff-mp','todo')] = {
 "wxml": '<view class="page"><view class="header"><text class="header-title">✅ 待办任务</text></view><view class="todo-list"><view class="todo-item {{item.priority === \'high\' ? \'high\' : \'\'}}" wx:for="{{todos}}" wx:key="id"><view class="todo-body"><text class="todo-title">{{item.title}}</text><text class="todo-meta">{{item.type}} · 截止 {{item.deadline}}</text></view><text class="todo-arrow">›</text></view></view></view>',
 "wxss": '.header { padding:14px 16px; background:#fff; border-bottom:1px solid #f0f0f0; }\n.header-title { font-size:18px; font-weight:700; }\n.todo-list { padding:12px 16px; }\n.todo-item { display:flex; align-items:center; padding:14px; background:#fff; border-radius:10px; margin-bottom:8px; }\n.todo-item.high { border-left:3px solid #e53935; }\n.todo-body { flex:1; }\n.todo-title { font-size:14px; font-weight:500; display:block; }\n.todo-meta { font-size:11px; color:#999; margin-top:2px; display:block; }\n.todo-arrow { color:#ccc; font-size:18px; }',
 "js": 'const API = require(\'../../utils/api\')\nPage({ data: { todos: [] }, onShow() { API.getTodos().then(todos => this.setData({ todos })) } })'
}

PAGES[('staff-mp','profile')] = {
 "wxml": '<view class="page"><view class="profile-header"><view class="avatar">👤</view><text class="name">{{user.displayName || \'店员\'}}</text><text class="role">{{user.role === \'admin\' ? \'管理员\' : user.role === \'staff\' ? \'店员\' : user.role}}</text></view><view class="menu-list"><view class="menu-item" bindtap="goOrders">📋 订单管理  ›</view><view class="menu-item" bindtap="goAttendance">⏰ 考勤打卡  ›</view><view class="menu-item" bindtap="goScheduling">📅 我的排班  ›</view><view class="menu-item" bindtap="goReceivable">💰 应收款  ›</view><view class="menu-item" bindtap="goReconciliation">📊 对账  ›</view></view><button class="logout-btn" bindtap="doLogout">退出登录</button></view>',
 "wxss": '.profile-header { padding:32px 20px; background:linear-gradient(135deg,#0052d9,#1a73e8); color:#fff; text-align:center; }\n.avatar { font-size:48px; margin-bottom:8px; }\n.name { font-size:20px; font-weight:700; display:block; }\n.role { font-size:12px; opacity:.8; margin-top:4px; display:block; }\n.menu-list { margin-top:12px; background:#fff; }\n.menu-item { padding:16px 20px; border-bottom:1px solid #f5f5f5; font-size:15px; }\n.logout-btn { margin:24px 16px; padding:14px; border-radius:10px; background:#fff; color:#e53935; border:1px solid #e53935; font-size:15px; width:calc(100% - 32px); text-align:center; }',
 "js": 'const API = require(\'../../utils/api\')\nPage({\n  data: { user: {} },\n  onShow() { const user = API.getCurrentUser(); if (user) this.setData({ user }) },\n  goOrders() { wx.navigateTo({ url: \'/pages/order-management/order-management\' }) },\n  goAttendance() { wx.navigateTo({ url: \'/pages/attendance/attendance\' }) },\n  goScheduling() { wx.navigateTo({ url: \'/pages/scheduling/scheduling\' }) },\n  goReceivable() { wx.navigateTo({ url: \'/pages/receivable/receivable\' }) },\n  goReconciliation() { wx.navigateTo({ url: \'/pages/reconciliation/reconciliation\' }) },\n  doLogout() { API.logout(); wx.reLaunch({ url: \'/pages/login/login\' }) }\n})'
}

TITLES = {
  ('customer-mp','room-list'): '选择包间',
  ('customer-mp','room-detail'): '房间详情',
  ('customer-mp','booking-confirm'): '确认预约',
  ('customer-mp','my-orders'): '我的订单',
  ('customer-mp','my-coupons'): '我的优惠券',
  ('customer-mp','coupon-verify'): '验券',
  ('customer-mp','room-control'): '房间智控',
  ('customer-mp','scan-landing'): '扫码落座',
  ('customer-mp','scan-order'): '扫码点单',
  ('customer-mp','scan-bill'): '房间账单',
  ('staff-mp','login'): '店员登录',
  ('staff-mp','dashboard'): '工作台',
  ('staff-mp','room-status'): '房态管理',
  ('staff-mp','device-monitor'): '设备监控',
  ('staff-mp','cleaning-task'): '保洁任务',
  ('staff-mp','todo'): '待办任务',
  ('staff-mp','profile'): '个人中心',
  ('staff-mp','device-control'): '设备控制',
  ('staff-mp','scene-control'): '场景控制',
  ('staff-mp','inspection'): '巡检',
  ('staff-mp','order-management'): '订单管理',
  ('staff-mp','product-management'): '商品管理',
  ('staff-mp','attendance'): '考勤',
  ('staff-mp','scheduling'): '排班',
  ('staff-mp','receivable'): '应收款',
  ('staff-mp','reconciliation'): '对账',
}

# Scan pages done via HTML earlier - add them
for (app, name) in [('customer-mp','scan-landing'), ('customer-mp','scan-order'), ('customer-mp','scan-bill')]:
    if (app, name) not in PAGES:
        print(f"  SKIP {app}/{name} - already exists as HTML")

# Generate placeholder pages for staff pages with templates
STAFF_PLACEHOLDER = {
 "wxml": '<view class="page"><view class="placeholder"><text class="ph-icon">🚧</text><text class="ph-text">开发中</text><text class="ph-desc">{{title}}</text></view></view>',
 "wxss": '.placeholder { display:flex; flex-direction:column; align-items:center; justify-content:center; padding:80px 20px; }\n.ph-icon { font-size:48px; margin-bottom:12px; }\n.ph-text { font-size:18px; color:#333; font-weight:600; }\n.ph-desc { font-size:13px; color:#999; margin-top:4px; }',
 "js": 'Page({ data: { title: \'\' }, onLoad(e) { this.setData({ title: \'功能开发中\' }) } })'
}

for name in ['device-control', 'scene-control', 'inspection', 'order-management', 'product-management', 'attendance', 'scheduling', 'receivable', 'reconciliation']:
    key = ('staff-mp', name)
    if key not in PAGES:
        PAGES[key] = STAFF_PLACEHOLDER

# ── Generate files ──

count = 0
for (app, name), files in PAGES.items():
    dir_path = os.path.join(BASE, app, 'pages', name)
    os.makedirs(dir_path, exist_ok=True)

    with open(os.path.join(dir_path, f'{name}.wxml'), 'w', encoding='utf-8') as f:
        f.write(files['wxml'])
    with open(os.path.join(dir_path, f'{name}.wxss'), 'w', encoding='utf-8') as f:
        f.write(files['wxss'])
    with open(os.path.join(dir_path, f'{name}.js'), 'w', encoding='utf-8') as f:
        f.write(files['js'])
    with open(os.path.join(dir_path, f'{name}.json'), 'w', encoding='utf-8') as f:
        title = TITLES.get((app, name), name)
        json.dump({"navigationBarTitleText": title, "usingComponents": {}}, f, ensure_ascii=False)
    count += 1
    print(f"  [{app}] {name}.wxml/wxss/js/json")

print(f"\n=== Done! Generated {count} page sets ===")
